# Generated by Django 5.2.4 on 2025-07-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_fotogaleria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('categoria', models.CharField(choices=[('academia', 'Academia'), ('eventos', 'Eventos')], max_length=10)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
