# Generated by Django 5.2.4 on 2025-07-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotoGaleria',
        ),
        migrations.RenameField(
            model_name='foto',
            old_name='data_envio',
            new_name='criado_em',
        ),
        migrations.AddField(
            model_name='foto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='categoria',
            field=models.CharField(choices=[('academia', 'Academia'), ('eventos', 'Eventos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='foto',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
