# Generated by Django 5.2.4 on 2025-07-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_delete_fotogaleria_rename_data_envio_foto_criado_em_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='PersonalTrainer',
        ),
    ]
